### ISSUE TITLE
Hiera 5 compatibility

### ISSUE THREAD

**Issue by soudaburger** [voxpupuli/hiera-file#23]
Is there any potential timeline for hiera 5 compatibility?

**Comment by ekohl** [comment]
I don't use this module and I'm not sure I understand its exact purpose in the modern puppet landscape. Doesn't hiera 5 do this sort of thing all out of the box?

**Comment by soudaburger** [comment]
@ekohl as has been expressed to me multiple times from multiple different people, Hiera is JUST a datastore and a key lookup.  It's not designed to serve up flat or binary files.  That being said, there is a HUGE need to fill that gap and this module does that perfectly.  But Hiera 5 changed everything and now all of the older stuff is simply incompatible.

**Comment by ekohl** [comment]
Given the current open issues and PRs I think this needs someone to take care of the module. If you're using this and interested I'm sure we can make you a member so you can take care of it. We can help you with all the infrastructure around the code but actual users are always better.

**Comment by soudaburger** [comment]
@ekohl , my only issue is that I don't have enough Ruby knowledge to write it correctly.  If that doesn't matter, I would be more than happy to contribute however I can.

**Comment by ekohl** [comment]
That shouldn't be an issue. Just ask for assistance whenever you don't know. Doesn't matter if it's IRC or in a PR

**Comment by soudaburger** [comment]
@ekohl sounds good... how can I reach you?  I'd like to take the initial conversation offline or to IRC until there is substantial comments or progress for the PR.... thanks!

**Comment by ekohl** [comment]
We are on ```#voxpupuli``` (freenode). There are also people who have the permissions to give you permissions.

**Comment by dhollinger** [comment]
Hiera 5 backends are built with Puppet Functions, either by using the Ruby API or the Puppet DSL native functions. This is a completely different "API" than what was used to build Hiera 3 backends.

This codebase cannot be used for a Hiera 5 backend and will require a new Puppet Module for the hiera-file backend for Hiera 5:

https://puppet.com/docs/puppet/5.3/hiera_custom_backends.html

**Comment by dhollinger** [comment]
Marking this as `wont-fix` as we can't deploy a Hiera 5 backend as a ruby gem.

**Comment by igalic** [comment]
i just replaced this gem with [12 lines of puppet](https://gist.github.com/02c682b1a5123c458a7c6ab538e6a29b)

```puppet
# replace hiera-file with a custom lookeup_key backend
function profiles::file::hiera_backend(
  String              $key,
  Hash                  $options,
  Puppet::LookupContext $context,
) {
  $contents = inline_template("<%= File.read('${options[path]}/${key}', mode: 'rb') {|f| f.read } if File.exists?('${options[path]}/${key}') %>")
  if $contents == '' or $contents == undef {
    $context.not_found
  }
  $contents
}
```

**Comment by soudaburger** [comment]
@igalic can you enlighten me a little further on how to actually implement that?  that would be amazing if that works!!!

**Comment by dhollinger** [comment]
@soudaburger Hiera 5 is implemented within Core Puppet and Hiera 5 backends are written as Puppet Functions using either the Puppet DSL Functions API or the Puppet Ruby Functions API.

Due to the API that is used, a new project would have to be created to release this.

**Comment by soudaburger** [comment]
@dhollinger what would it take to get that done?

**Comment by dhollinger** [comment]
@soudaburger At this time, it'd probably be best to take what @igalic created and test that in your network or create a new project for the File Backend. 

Unfortunately, we don't have a lot of time to build a new Hiera 5 backend project.
